package com.codepath.apps.restclienttemplate.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MEDIA.
 */
public class Media {

    private Long internalId;
    private Long id;
    private String type;
    private String media_url;
    private Long inTweets;

    public Media() {
    }

    public Media(Long internalId) {
        this.internalId = internalId;
    }

    public Media(Long internalId, Long id, String type, String media_url, Long inTweets) {
        this.internalId = internalId;
        this.id = id;
        this.type = type;
        this.media_url = media_url;
        this.inTweets = inTweets;
    }

    public Long getInternalId() {
        return internalId;
    }

    public void setInternalId(Long internalId) {
        this.internalId = internalId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getMedia_url() {
        return media_url;
    }

    public void setMedia_url(String media_url) {
        this.media_url = media_url;
    }

    public Long getInTweets() {
        return inTweets;
    }

    public void setInTweets(Long inTweets) {
        this.inTweets = inTweets;
    }

}
